import "./globals.css";
import type { Metadata } from "next";

import ThemeRegistry from "@/components/ThemeRegistry";

import Header from "@/components/Header";

import { SearchProvider } from "./context/SearchContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <ThemeRegistry options={{ key: "mui" }}>
          <SearchProvider>  
            {children}
          </SearchProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
